export default [
  { css: '/images/mansory/image1.webp', height: 150 },
  { css: '/images/mansory/image2.webp', height: 300 },
  { css: '/images/mansory/image1.webp', height: 300 },
  { css: '/images/mansory/image2.webp', height: 300 },
  { css: '/images/mansory/image1.webp', height: 300 },
  { css: '/images/mansory/image2.webp', height: 300 },
  { css: '/images/mansory/image1.webp', height: 200 },
  { css: '/images/mansory/image2.webp', height: 300 },
  { css: '/images/mansory/image1.webp', height: 200 },
  { css: '/images/mansory/image2.webp', height: 400 },
  { css: '/images/mansory/image1.webp', height: 200 },
  { css: '/images/mansory/image2.webp', height: 150 },
  { css: '/images/mansory/image1.webp', height: 400 },
  // { css: 'https://images.pexels.com/photos/380337/pexels-photo-380337.jpeg', height: 200 },
]
