export default [
  { css: '/images/mansory/gallery-1.webp', height: 150 },
  { css: '/images/mansory/gallery-2.webp', height: 300 },
  { css: '/images/mansory/gallery-3.webp', height: 300 },
  { css: '/images/mansory/gallery-4.webp', height: 300 },
  { css: '/images/mansory/gallery-5.webp', height: 300 },
  { css: '/images/mansory/gallery-6.webp', height: 300 },
  { css: '/images/mansory/gallery-7.webp', height: 200 },
  { css: '/images/mansory/gallery-8.webp', height: 300 },
  { css: '/images/mansory/gallery-9.webp', height: 200 },
  { css: '/images/mansory/gallery-10.webp', height: 400 },
  { css: '/images/mansory/gallery-11.webp', height: 200 },
  { css: '/images/mansory/gallery-12.webp', height: 150 },
  { css: '/images/mansory/gallery-13.webp', height: 400 },
  { css: '/images/mansory/gallery-14.webp', height: 200 },
]
